name: CI Fraud Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark pytest nbformat nbconvert nbqa flake8 black isort

      - name: Format notebooks with Black
        run: |
          # Formate automatiquement les notebooks au lieu de bloquer la CI
          python -m nbqa black notebooks/

      - name: Lint notebooks with Flake8
        run: |
          # Utilise explicitement la configuration .flake8
          python -m nbqa flake8 notebooks/ --config=.flake8

      - name: Run PySpark tests
        run: pytest tests/