name: CI Fraud Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyspark
          pip install pytest
          pip install nbformat nbconvert
          pip install nbqa
          pip install flake8 black isort
      
      - name: Lint notebooks with nbQA
        run: |
          pip install nbqa flake8
          nbqa flake8 notebooks/
          nbqa black --check notebooks/
          python -m nbqa flake8 notebooks/
      
      - name: Run PySpark tests
        run: pytest tests/

